build:
  environment:
    python: "pypy3.7-7.3.4"  # Use PyPy 3.7 (7.3.4)
  dependencies:
    before:
      - python3 -m ensurepip  # Ensure pip is installed for PyPy
      - python3 -m pip install --upgrade pip
      - pip install telebot pytz flask aiogram pymongo pyTelegramBotAPI python-telegram-bot motor
  
  tests:
    override:
      - chmod +x smokey || true
      - chmod +x run_ninja.sh  # Ensure the wrapper script is executable
      - ./run_ninja.sh  # Run the wrapper script
